a15

diff --git a/.github/workflows/vmcicd.yml b/.github/workflows/vmcicd.yml
--- a/.github/workflows/vmcicd.yml
+++ b/.github/workflows/vmcicd.yml
@@ -13,6 +13,10 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
+      - name: Ensure directory exists and navigate to it
+        run: |
+          cd /home/divya/testaction/node_todo_cicd_master || { echo "Directory not found"; exit 1; }
+
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
@@ -22,9 +26,10 @@ jobs:
         run: npm ci  # Install dependencies
 
       - name: Build and Deploy
-        run: |
-          npm run build  # Build your application
-          npm run deploy  # Deploy your application
+        run: npm run build  # Build your application
+
+      - name: Deploy Application
+        run: npm run deploy  # Deploy your application
 
       - name: SSH into VM and restart application
         uses: appleboy/ssh-action@master
